### ISSUE TITLE
Failed to open smoking.mln

### ISSUE THREAD

**Issue by ghost** [dportabella/docker-alchemy2#1]
I seem to be having an issue (after the learnwts cmd) opening the "smoking.mln" file. I can view this file using the Linux text editor, but it appears like the system doesn't have access to the file after I enter the commands below.

$ docker run -ti --name alchemy2 -v /d/Users/david/data/:/data dportabella/docker-alchemy2 bash
learnwts -d -i /data/smoking.mln -o /data/result/smoking-out.mln -t /data/smoking-train.db -ne Smokes,Cancer

Any thoughts?

**Comment by dportabella** [comment]
what is the exact error?
before running `learnwts`, did you run `mkdir /data/result/`?

otherwise, run as follows:
```
learnwts -d -i /data/smoking.mln -o /data/smoking-out.mln -t /data/smoking-train.db -ne Smokes,Cancer
```

**Comment by ghost** [comment]
dportabella-

Thanks for the reply. I was able to fix the primary issue (ERROR: smoking.mln not found) but correct the VirtualBox shared drive folder.

Now I'm currently having an error:  
Error in smoking.mln12: line 2, col -1: parse error, unexpected '\n', expecting ZZ_NUM. Num of errors detected =1

Not sure if you've received this error, might be something for the listserve (if anyone is paying attention anymore).
Thanks
Bob

**Comment by ghost** [comment]
Update - I refreshed the data and everything worked fine. Thanks!
